### ISSUE TITLE
Compiling on OS X 10.8.5 boost issue

### ISSUE THREAD

**Issue by dejl** [AnotherTest/-English#9]
MacBookPro:-English daniel$ make
Scanning dependencies of target NotEnglish
[ 14%] Building CXX object CMakeFiles/./bin/NotEnglish.dir/DataHandler.cpp.o
In file included from /Users/daniel/tmp/-English/DataHandler.cpp:3:
In file included from /Users/daniel/tmp/-English/DataHandler.h:7:
In file included from /Users/daniel/tmp/-English/Variable.h:7:
In file included from /Users/daniel/tmp/-English/Variant.h:8:
In file included from /usr/local/include/boost/variant.hpp:17:
In file included from /usr/local/include/boost/variant/variant.hpp:31:
In file included from /usr/local/include/boost/variant/detail/initializer.hpp:23:
/usr/local/include/boost/variant/detail/move.hpp:100:12: error: no member named
      'move' in namespace 'std'
using std::move;
      ~~~~~^
/usr/local/include/boost/variant/detail/move.hpp:139:36: error: no type named
      'move' in namespace 'boost::detail::variant'
    T tmp( boost::detail::variant::move(lhs) );
           ~~~~~~~~~~~~~~~~~~~~~~~~^
/usr/local/include/boost/variant/detail/move.hpp:140:35: error: no member named
      'move' in namespace 'boost::detail::variant'
    lhs = boost::detail::variant::move(rhs);
          ~~~~~~~~~~~~~~~~~~~~~~~~^
/usr/local/include/boost/variant/detail/move.hpp:141:35: error: no member named
      'move' in namespace 'boost::detail::variant'
    rhs = boost::detail::variant::move(tmp);
          ~~~~~~~~~~~~~~~~~~~~~~~~^
^[In file included from /Users/daniel/tmp/-English/DataHandler.cpp:3:
In file included from /Users/daniel/tmp/-English/DataHandler.h:7:
In file included from /Users/daniel/tmp/-English/Variable.h:7:
In file included from /Users/daniel/tmp/-English/Variant.h:8:
In file included from /usr/local/include/boost/variant.hpp:17:
In file included from /usr/local/include/boost/variant/variant.hpp:31:
/usr/local/include/boost/variant/detail/initializer.hpp:122:60: error: no member
      named 'move' in namespace 'boost::detail::variant'
                new(dest) value_T( boost::detail::variant::move(operand) );
                                   ~~~~~~~~~~~~~~~~~~~~~~~~^
In file included from /Users/daniel/tmp/-English/DataHandler.cpp:3:
In file included from /Users/daniel/tmp/-English/DataHandler.h:7:
In file included from /Users/daniel/tmp/-English/Variable.h:7:
In file included from /Users/daniel/tmp/-English/Variant.h:8:
In file included from /usr/local/include/boost/variant.hpp:17:
/usr/local/include/boost/variant/variant.hpp:461:52: error: no member named
      'move' in namespace 'boost::detail::variant'
        new(storage_) T( ::boost::detail::variant::move(operand.get()) );
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~^
/usr/local/include/boost/variant/variant.hpp:469:51: error: no member named
      'move' in namespace 'boost::detail::variant'
        new(storage_) T(::boost::detail::variant::move(operand));
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~^
/usr/local/include/boost/variant/variant.hpp:559:41: error: no member named
      'move' in namespace 'boost::detail::variant'
            = ::boost::detail::variant::move(static_cast<backup_holder<T...
              ~~~~~~~~~~~~~~~~~~~~~~~~~~^
/usr/local/include/boost/variant/variant.hpp:568:41: error: no member named
      'move' in namespace 'boost::detail::variant'
            = ::boost::detail::variant::move(static_cast<backup_holder<T...
              ~~~~~~~~~~~~~~~~~~~~~~~~~~^
/usr/local/include/boost/variant/variant.hpp:583:49: error: no member named
      'move' in namespace 'boost::detail::variant'
        lhs_content = ::boost::detail::variant::move(_static_cast<T_ >(r...
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~^
/usr/local/include/boost/variant/variant.hpp:689:41: error: no member named
      'move' in namespace 'boost::detail::variant'
        lhs = ::boost::detail::variant::move(rhs_);
              ~~~~~~~~~~~~~~~~~~~~~~~~~~^
/usr/local/include/boost/variant/variant.hpp:767:41: error: no type named 'move'
      in namespace 'boost::detail::variant'
              ::boost::detail::variant::move(lhs_content)
              ~~~~~~~~~~~~~~~~~~~~~~~~~~^
/usr/local/include/boost/variant/variant.hpp:783:49: error: no member named
      'move' in namespace 'boost::detail::variant'
                      ::boost::detail::variant::move(backup_lhs_content)
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~^
/usr/local/include/boost/variant/variant.hpp:1496:71: error: no member named
      'move' in namespace 'boost::detail::variant'
  ...return initializer::initialize(storage_, detail::variant::move(operand) );
                                              ~~~~~~~~~~~~~~~~~^
/usr/local/include/boost/variant/variant.hpp:1577:36: error: no member named
      'move' in namespace 'boost::detail::variant'
                , detail::variant::move(operand)
                  ~~~~~~~~~~~~~~~~~^
/usr/local/include/boost/variant/variant.hpp:1661:32: error: no member named
      'move' in namespace 'boost::detail::variant'
              detail::variant::move(operand), 1L
              ~~~~~~~~~~~~~~~~~^
/usr/local/include/boost/variant/variant.hpp:1692:53: error: no member named
      'move' in namespace 'boost::detail::variant'
        convert_construct_variant( detail::variant::move(operand) );  
                                   ~~~~~~~~~~~~~~~~~^
/usr/local/include/boost/variant/variant.hpp:1751:45: error: no member named
      'move' in namespace 'boost::detail::variant'
        convert_construct( detail::variant::move(operand), 1L);
                           ~~~~~~~~~~~~~~~~~^
/usr/local/include/boost/variant/variant.hpp:1846:40: error: no member named
      'move' in namespace 'boost::detail::variant'
                RhsT( detail::variant::move(temp) ); // nothrow
                      ~~~~~~~~~~~~~~~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: **\* [CMakeFiles/./bin/NotEnglish.dir/DataHandler.cpp.o] Error 1
make[1]: **\* [CMakeFiles/./bin/NotEnglish.dir/all] Error 2
make: **\* [all] Error 2

**Comment by AnotherTest** [comment]
It seems like your compiler doesn't fully support C++11. It complains about std::move. Could you tell me what your compiler (and version) is?

It may be because the current makefile is made specifically for g++, which uses the flag -std=c++11 to enable C++11 support. If you're using a different compiler, this might have to be modified. Maybe you should try modifying CMakeLists.txt. I will try to provide a more permanent solution as well.

**Comment by dejl** [comment]
MacBookPro:~ daniel$ g++ -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 5.0 (clang-500.2.76) (based on LLVM 3.3svn)
Target: x86_64-apple-darwin12.5.0
Thread model: posix

I'm pretty sure this supports C++11?

**Comment by dejl** [comment]
Got it working with GCC/G++ 4.8.1 installed via homebrew "brew install gcc48"
Maybe clang/llvm doesn't support C++11 fully or has a different option?
